# Programming Assignment 2
### Normalization Problem

In [3]:
import numpy as np

In [4]:


# Random 5x5 ndarray
X = np.random.rand(5, 5)

# Normalize the ndarray
normalized_X = (X - X.mean()) / X.std()

# Original / normalized
print(f"Orig:\n {X}\n")
print(f"Norm:\n {normalized_X}")

Orig:
 [[0.51478061 0.80345792 0.62968193 0.92841289 0.09024046]
 [0.89554512 0.45655057 0.79722145 0.89725721 0.71467713]
 [0.40251815 0.304411   0.28972314 0.85954808 0.80793295]
 [0.01222776 0.77373097 0.13792825 0.16305959 0.25668629]
 [0.18488864 0.87136018 0.21609973 0.28125021 0.44967161]]

Norm:
 [[ 0.01757819  0.98854886  0.40405059  1.40883689 -1.41036929]
 [ 1.29828563 -0.17827947  0.96757239  1.30404427  0.68993327]
 [-0.36001837 -0.6900033  -0.73940616  1.17720902  1.0036007 ]
 [-1.67276624  0.88856181 -1.24997066 -1.16544098 -0.85052613]
 [-1.09201862  1.2169392  -0.98703964 -0.767905   -0.20141697]]
